title: (RE)CLAIME
description: application progress
lang: en

baseurl: "/claime"

nav:
  - label: home
    url: /
  - label: tasks
    url: /tasks/
  - label: meetings
    url: /meetings/

markdown: kramdown
theme: null
